# Generated by Django 5.2.7 on 2025-11-15 10:25

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(default=reports.models.generate_case_id, editable=False, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('Bullying', 'Bullying & Harassment'), ('Safety', 'Safety & Security Concern'), ('Academic', 'Academic Issue / Unfair Treatment'), ('Conduct', 'Teacher / Staff Conduct'), ('Neglect', 'Child Neglect or Abuse'), ('Other', 'Other Concern')], max_length=20)),
                ('school_name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('reporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Action in Progress', 'Action in Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('User', 'User (Parent/Student)'), ('Authority', 'Authority (Admin)')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reports.report')),
            ],
        ),
    ]
