# Generated by Django 5.2.7 on 2025-11-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_forumpost_forumreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Mental Health', 'Mental Health & Counseling'), ('Legal Aid', 'Legal Aid'), ('Support Group', 'Support Group'), ('Online Safety', 'Online Safety'), ('Emergency', 'Emergency Hotline')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
